# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='services',
            field=models.ManyToManyField(null=True, related_name='stations', to='app.Service'),
        ),
    ]
